const navigationRoutes = {
    login: "Login",
    register: "Register",
    createPinScreen: "CreatePinScreen",
    homeNavigation: "HomeNavigation",
    homeScreen: "HomeScreen",
    grtNavigation: "GRTNavigation",
    grtFormScreen: "GRTFormScreen",
    groupNavigation: "GroupNavigation",
    groupFormScreen: "GroupFormScreen",
    bottomNavigationPaper: "BottomNavigationPaper",
    loanRecoveryNavigation: "LoanRecoveryNavigation",
    searchLoanRecoveryScreen: "SearchLoanRecoveryScreen",
    recoveryGroupScreen: "RecoveryGroupScreen",
    recoveryMemberScreen: "RecoveryMemberScreen",
    searchNavigation: "SearchNavigation",
    searchByGroupScreen: "SearchByGroupScreen",
    coGroupFormExtendedScreen: "COGroupFormExtendedScreen",
    searchByMemberScreen: "SearchByMemberScreen",
    searchByCOScreen: "SearchByCOScreen",
    availableFormsScreen: "AvailableFormsScreen",
    formsAgainstCOScreen: "FormsAgainstCOScreen",
    memberDetailsAllFormScreen: "MemberDetailsAllFormScreen",
    searchScreen: "SearchScreen",
    settingsNavigation: "SettingsNavigation",
    settingsScreen: "SettingsScreen",
    noInternetScreen: "NoInternetScreen",

    bmPendingLoansNavigation: "BMPendingLoansNavigation",
    bmPendingLoansScreen: "BMPendingLoansScreen",
    bmPendingLoanFormScreen: "BMPendingLoanFormScreen",
}

export default navigationRoutes