const navigationRoutes = {
    login: "Login",
    register: "Register",
    createPinScreen: "CreatePinScreen",
    homeScreen: "HomeScreen",
    settingsScreen: "SettingsScreen",
    bottomNavigationPaper: "BottomNavigationPaper",
    homeNavigation: "HomeNavigation",
    settingsNavigation: "SettingsNavigation",
    productsScreen: "ProductsScreen",
    categoriesScreen: "CategoriesScreen",
    categoryProductsScreen: "CategoryProductsScreen",
    cartScreen: "CartScreen",
    allBillsScreen: "AllBillsScreen",
    masterChooseScreen: "MasterChooseScreen",
    // itemMasterScreen: "ItemMasterScreen",
    printMain: "PrintMainScreen",
    customerDetailsFillScreen: "CustomerDetailsFillScreen",
    cancelBillScreen: "CancelBillScreen",
    refundItemsScreen: "RefundItemsScreen",
    receiptsAgainstMobileScreen: "ReceiptsAgainstMobileScreen",
    refundItemsDataScreen: "RefundItemsDataScreen",
    reportsNavigation: "ReportsNavigation",
    reportsScreen: "ReportsScreen",
    moreScreen: "MoreScreen",
    saleReportScreen: "SaleReportScreen",
    saleSummaryScreen: "SaleSummaryScreen",
    itemReportScreen: "ItemReportScreen",
    gstStatementReportScreen: "GstStatementReportScreen",
    gstSummaryReportScreen: "GstSummaryReportScreen",
    stockReportScreen: "StockReportScreen",
    cancelledBillsReportScreen: "CancelledBillsReportScreen",
    daybookReportScreen: "DaybookReportScreen",
    refundReportScreen: "RefundReportScreen",
    creditReportScreen: "CreditReportScreen",
    userwiseReportScreen: "UserwiseReportScreen",
    customerLedgerScreen: "CustomerLedgerScreen",
    dueReportScreen: "DueReportScreen",
    recoveryReportScreen: "RecoveryReportScreen",
    // refundItemsReportScreen: "RefundItemsReportScreen",
    headerFooterScreen: "HeaderFooterScreen",
    manageProductsScreen: "ManageProductsScreen",
    manageCategoriesScreen: "ManageCategoriesScreen",
    manageUnitsScreen: "ManageUnitsScreen",
    inventoryScreen: "InventoryScreen",
    // receiptSettingsEditScreen: "ReceiptSettingsEditScreen",
    settingsMasterScreen: "ReceiptSettingsEditScreen",
    generalSettingsScreen: "GeneralSettingsScreen",
    discountSettingsScreen: "DiscountSettingsScreen",
    gstSettingsScreen: "GstSettingsScreen",
    logoUploadScreen: "LogoUploadScreen",
    upiGenerateScreen: "upiGenerateScreen",
    changePinScreen: "changePinScreen",
    forgotPinScreen: "ForgotPinScreen",
    profileScreen: "ProfileScreen",
    noInternetScreen: "NoInternetScreen",
    searchBillsByDateScreen: "SearchBillsByDateScreen",
    // searchBillsByMobileNumberScreen: "SearchBillsByMobileNumberScreen",
    cancelBillsScreen: "CancelBillsScreen",
    searchBillsByItemScreen: "SearchBillsByItemScreen",
    refundReprintScreen: "RefundReprintScreen",
    recoveryAmountScreen: "RecoveryAmountScreen",
    cameraScreen: "CameraScreen",

    calculateModeNavigation: "CalculateModeNavigation",
    calculateModeScreen: "CalculateModeScreen",
    calculateModeBillScreen: "CalculateModeBillScreen",
    saleReportCalculateModeScreen: "SaleReportCalculateModeScreen",
}

export default navigationRoutes