import { BASE_URL } from "./config"

export const ADDRESSES = {
    LOGIN: `${BASE_URL}/login_app`,
    // UPDATE_LOGIN_FLAG: `${BASE_URL}/api/update_login_status`,
    // RECEIPT_SETTINGS: `${BASE_URL}/api/receipt_settings`,
    GROUP_NAMES: `${BASE_URL}/get_group`,
    GROUP_NAMES_ES: `${BASE_URL}/get_group_add`,
    GET_RELIGIONS: `${BASE_URL}/get_religion`,
    GET_CASTES: `${BASE_URL}/get_caste`,
    GET_EDUCATIONS: `${BASE_URL}/get_education`,
    SAVE_BASIC_DETAILS: `${BASE_URL}/save_basic_dtls`,
    FETCH_CLIENT_DETAILS: `${BASE_URL}/fetch_validation`,
    SAVE_GROUP: `${BASE_URL}/save_group`,

    GET_STATES: `${BASE_URL}/get_state`,
    GET_DISTS: `${BASE_URL}/get_district`,
    GET_BLOCKS: `${BASE_URL}/get_block`,

    FETCH_BASIC_DETAILS: `${BASE_URL}/fetch_basic_dtls`,
    FETCH_PURPOSE_OF_LOAN: `${BASE_URL}/get_purpose`,
    FETCH_SUB_PURPOSE_OF_LOAN: `${BASE_URL}/get_sub_purpose`,
    FETCH_FORMS: `${BASE_URL}/fetch_form_dtls`,
    EDIT_BASIC_DETAILS: `${BASE_URL}/edit_basic_dtls`,
    SAVE_OCCUPATION_DETAILS: `${BASE_URL}/save_occup_dtls`,
    FETCH_OCCUPATION_DETAILS: `${BASE_URL}/fetch_occup_dtls`,

    SAVE_HOUSEHOLD_DETAILS: `${BASE_URL}/save_household_dtls`,
    FETCH_HOUSEHOLD_DETAILS: `${BASE_URL}/fetch_household_dtls`,
    SAVE_FAMILY_DETAILS: `${BASE_URL}/save_family_dtls`,
    FETCH_FAMILY_DETAILS: `${BASE_URL}/fetch_family_dtls`,
    DELETE_FORM: `${BASE_URL}/delete_form`,
    SEARCH_GROUP: `${BASE_URL}/search_group`,
    EDIT_GROUP: `${BASE_URL}/edit_group`,
    MEMBER_DETAILS: `${BASE_URL}/member_dt`,
    SEARCH_MEMBER: `${BASE_URL}/search_member`,
    SEARCH_CO: `${BASE_URL}/search_co`,
    GET_GRT_DETAILS: `${BASE_URL}/get_grt_dtls`,
    GET_FORM_AGAINST_CO: `${BASE_URL}/get_form_against_co`,
    FINAL_SUBMIT: `${BASE_URL}/final_submit`,
    SEARCH_GROUP_RECOVERY: `${BASE_URL}/search_group_app`,
    DEMANDREPORT: `${BASE_URL}/get_demand_data`,
    GROUPWISERECOVERYREPORT: `${BASE_URL}/group_wise_recov_app`,
    LOAN_RECOVERY_EMI: `${BASE_URL}/recovery_transaction`,
    BM_SEARCH_PENDING_FORM: `${BASE_URL}/bm_search_pending_form`,

    VIEW_LOAN_TNX: `${BASE_URL}/view_transaction`,
    DELETE_TNX: `${BASE_URL}/remove_trans`,
    GET_BANKS: `${BASE_URL}/get_bank`,

    CLOCK_IN: `${BASE_URL}/save_in_attendance`,
    CLOCK_OUT: `${BASE_URL}/save_out_attendance`,
    CLOCKED_IN_DATE_TIME: `${BASE_URL}/get_attendance_dtls`,

    DASHBOARD_DETAILS: `${BASE_URL}/dashboard_dtls`,
    DASHBOARD_CASH_RECOV_DETAILS: `${BASE_URL}/dashboard_dtls_cash_recov`,
    DASHBOARD_BANK_RECOV_DETAILS: `${BASE_URL}/dashboard_dtls_bank_recov`,
    DASHBOARD_DETAILS_BM: `${BASE_URL}/dashboard_dtls_bm`,
    DASHBOARD_CASH_DETAILS_BM: `${BASE_URL}/dashboard_dtls_cash_recov_bm`,
    DASHBOARD_BANK_DETAILS_BM: `${BASE_URL}/dashboard_dtls_bank_recov_bm`,

    // MEMBERWISE_RECOVERY_REPORT: `${BASE_URL}/member_wise_recovery`,
    MEMBERWISE_RECOVERY_REPORT: `${BASE_URL}/memb_wise_recov_app`,
    MEMBERWISE_DISBURSEMENT_REPORT: `${BASE_URL}/member_wise_disb`,
    ATTENDANCE_REPORT: `${BASE_URL}/attendance_report`,
}